### ISSUE TITLE
/clist Remove buttons are all broken, except the top entry on the list

### ISSUE THREAD

**Issue by Zebouski** [Junie-774/CraftingList#1]
Hey, thanks for this insanely useful plugin, it has reinvigorated my desire to do crafting and gathering

If I have more than one entry on the /clist panel, then the remove buttons on the right side, you click them and nothing happens. Only the entry that's at the top of the list, does Remove work. I checked the dalmud logs and nothing is logged when i click the nonworking buttons. If this could be fixed that would be sick awesome

**Comment by Junie-774** [comment]
Imgui hard ;w;. Fixed!
