### ISSUE TITLE
Crafting list runs into error when crafting recipes that outputs more than one item

### ISSUE THREAD

**Issue by lyndistt** [Junie-774/CraftingList#10]
This error message pops up whenever I try to make a high(80-89) level recipe that outputs 2-3 items, often from Alchemist or Culinarian recipes:

[CraftingList] An error occured validating the list. Please make sure all of your amounts are correct, and that all of your macros are selected.

However, this doesn't happen with a low level recipe, like honey.
I've checked that I have enough mats, tried making 1, tried max and made sure that the macro is working with a "manual" macro craft. The macro is also one button.

Could it be that the plugin is checking itself for error, since recipes input is 1 and output is 3, it sends an error to not process the crafting command?

**Comment by Junie-774** [comment]
I ran into this issue earlier and fixed it, forgot to version bump. Version 1.9.2 should address this, feel free to open this issue again if the problem persists
