### ISSUE TITLE
"Ignore <wait.x> and wait intelligently" feature not working

### ISSUE THREAD

**Issue by lyndistt** [Junie-774/CraftingList#11]
On the latest version, crafting stuff with macros gives this error, regardless of crafts. I've tried with 1 macro recipe, 2 macro recipes, and trained eye recipes, and all of them gives this error below:

https://cdn.discordapp.com/attachments/984006071293214761/1067079937015689226/image.png

I've also tried playing around with the "wait after clicking synthesis/executing macro" timers and different combinations of turning those off and on. The only workaround that seems to fix it for me right now is to turn off "Ignore wait''.

**Comment by Junie-774** [comment]
Which type of macro are you using?
Can you provide me an image of what happens in `/xllog` when you do this with the log level set to Debug?

**Comment by lyndistt** [comment]
![image](https://user-images.githubusercontent.com/123083701/214159554-7c681377-f888-478c-aff5-27f05cada91a.png)

I used In-Plugin Macros.
The first row of error is for this macro, while crafting Rarefied Lemonade:

/ac "Trained Eye" <wait.3>
/ac Groundwork <wait.3>
/ac Groundwork <wait.3>

The second row of error is this macro, while crafting AR-Caean Velvet:

/ac "Muscle Memory" <wait.3>
/ac Manipulation <wait.2>
/ac "Waste Not II" <wait.2>
/ac Innovation <wait.2>
/ac Groundwork <wait.3>
/ac "Preparatory Touch" <wait.3>
/ac "Preparatory Touch" <wait.3>
/ac "Preparatory Touch" <wait.3>
/ac Innovation <wait.2>
/ac "Preparatory Touch" <wait.3>
/ac "Great Strides" <wait.2>
/ac "Byregot's Blessing" <wait.3>
/ac Groundwork <wait.3>

Let me know if there is any other info or log that you need :)

**Comment by Junie-774** [comment]
Hmm, alright. And can you send me an image of your experimental tab?'

Oop, I've done some testing on my end. The fields "WaitForConditionLoop", "AfterWaitForCondition", and "CraftingActionMaxDelay" somehow got sent out with 0 as their default values, which is uhh, very incorrect. I tried sending out a fix that would reset them if they were found to be 0 but that didn't work. For now you can manually change them and they'll save, but that's what's going on. I'll be releasing a (hopefully) working fix for this issue soon

**Comment by Junie-774** [comment]
Released a fix that should work, feel free to reopen if it doesn't
