### ISSUE TITLE
Shared Ingot Recipe issue

### ISSUE THREAD

**Issue by Iondite** [Junie-774/CraftingList#14]
I tried crafting shared recipes with arm bsm and when I specify arm version in UI it defaults to craft bsm version of ingot recipes giving me error, even though i have the matireals. It works as usual when i specify bsm recipe.

**Comment by Junie-774** [comment]
This old ghost coming back to bite me. Will take a bit to fix but it's comin

**Comment by Junie-774** [comment]
I lied it was easier than I thought to fix.
