### ISSUE TITLE
Cannot auto repair in Japanese version

### ISSUE THREAD

**Issue by cannypp** [Junie-774/CraftingList#15]
Cannot auto repair in Japanese version because /action repair command cannot be run in Japanese version
It have to use /action 修理 in Japanese version

**Comment by Junie-774** [comment]
Ah, yeah ran into this issue when making localization for french and german. Will feex. Do you have any resources for command names in japanese? The one I was using for french and german didn't have the japanese equivalents for some reason.

**Comment by cannypp** [comment]
https://strings.wakingsands.com/
This is a Chinese site to find the Chinese, Japanese and English version of data from client. The data is 5.0
You can search the PlaceName like this
repair filename:PlaceName
The Column 日语 is Japanese
Command is same as English, but action name is Japanese

**Comment by Junie-774** [comment]
Thank you! I'll save this for more localization issues. I think i've fixed the problem, but I'm not on the JP client so I can't test. I'll close the issue when I push the fix, but please feel free to reopen this if the fix doesn't work
