### ISSUE TITLE
+ Button disappears when selecting HQ ingredient 

### ISSUE THREAD

**Issue by bloodclot** [Junie-774/CraftingList#17]
https://user-images.githubusercontent.com/10051144/217113528-5f71d8c3-f0f9-41de-89ff-b6f28f6c0008.mp4

**Comment by bloodclot** [comment]
https://user-images.githubusercontent.com/10051144/217113978-efd06505-7936-495c-bfc0-a0ea8b0b0218.mp4

**Comment by Junie-774** [comment]
This issue seems to go away on my dev build, I dunno what I changed but I already fixed it, will be out with next update
