### ISSUE TITLE
Window occasionally disappears with some UI elements still present

### ISSUE THREAD

**Issue by OtisOathkeeper** [Junie-774/CraftingList#18]
I've found that the clist window will close out in an incomplete way, and the only way I've restored it, is by disabling and reenabling it through dalamud. Pictures attached showing the window in a normal state, and after it disappears, leaving the duration element on screen. The window disappeared once after cancelling a craft, and once more after I was switching between tabs. 

As a separate issue, there does not seem to be a donate option. I'd love to buy you a coffee for making such a wonderful tool. ♥

Normal window 
![Normal](https://user-images.githubusercontent.com/20195700/219976240-35bd7542-5a56-4673-a759-c301756e6921.png)

After window disappears
![Disappeared](https://user-images.githubusercontent.com/20195700/219976078-afe2fb7e-ad0f-4e60-bf03-f42b3703ee5f.png)

**Comment by OtisOathkeeper** [comment]
Forgot my xllog, so here it is! This error repeats all the way up. 

![xllog](https://user-images.githubusercontent.com/20195700/219976389-1916edd0-1d1d-408b-bab1-d338469c0a4c.png)

**Comment by Junie-774** [comment]
So, I *think* I know what's causing that and have pushed a tentative fix. It doesn't happen on my machine so i'm not sure how to reproduce it. Let me know if the tentative fix works and I'll close the issue!

The other problem has been fixed as well ^^

**Comment by OtisOathkeeper** [comment]
Woahhhh, got a completely different issue. I was churning out some bangles when the craft list got stopped. My craft window looks like this, and xllog doesn't have anything besides dalamud loading plugins. It almost looks like network latency just taking its time loading the log, but it stays stuck like this and isn't interactable. 

![ffxiv_dx11_Wvq5rfKgpJ](https://user-images.githubusercontent.com/20195700/220235552-01b2ea46-f8fe-4d97-8856-8cfb73e35ae9.png)

This persisted after relogging. Restarting the entire game restored the crafting log.

**Comment by Junie-774** [comment]
hmm, that's concerning. has it happened more than once?

**Comment by OtisOathkeeper** [comment]
Just once, hasn't happened since. Will let you know + supply xllog if it comes up.

**Comment by OtisOathkeeper** [comment]
Neither issue has happened since. Yesterday was rife with latency issues in XIV, but they aren't present today.

**Comment by Junie-774** [comment]
My guess is that it was a combination of latency issues and some weirdness with opening the crafting log programmatically. I'll close the issue but feel free to reopen if it happens again
