### ISSUE TITLE
Clist start the craft, but do not use the Macro

### ISSUE THREAD

**Issue by Hecterus** [Junie-774/CraftingList#24]
Heyho Together,

After the update crafttool starts to pick the craft but do not start to use the Macro.

![grafik](https://github.com/Junie-774/CraftingList/assets/147446877/7d3b5e24-2eb7-49e4-9f7f-6469dc214db6)

Maybe you have an solution for this Problem?

**Comment by Junie-774** [comment]
closing this on the assumption that it was fixed with the api 9 fixes, reopen or submit another if i didn't fix it
