### ISSUE TITLE
7.0 update

### ISSUE THREAD

**Issue by Gasteno** [Junie-774/CraftingList#26]
thanks for mantaining this plugin. Any chance this gets updated for 7.0? Thx!

**Comment by dazemc** [comment]
https://dazemc.github.io/ffxiv-craft/

Until they get updates at least. This implementation here is superior though, I've been looking at it while refactoring 

You can also check out craftimizer,
https://github.com/WorkingRobot/Craftimizer

**Comment by Junie-774** [comment]
I'll be updating this as soon as I'm done with the elden ring DLC, will also potentially be taking a look at new features

**Comment by Junie-774** [comment]
feexd

**Comment by Gasteno** [comment]
> feexd

We are grateful. ty so much.

**Comment by Gasteno** [comment]
> https://dazemc.github.io/ffxiv-craft/
> 
> Until they get updates at least. This implementation here is superior though, I've been looking at it while refactoring
> 
> You can also check out craftimizer, https://github.com/WorkingRobot/Craftimizer

This plugin doesnt compare to those. sorry. Junie's CraftingList is elite.
