### ISSUE TITLE
Food "None" Not Working

### ISSUE THREAD

**Issue by truduEprocEss** [Junie-774/CraftingList#5]
Hey there!
I love the plugin and I think you're doing a wonderful job. I found an issue that I hope can be addressed:

If the plugin was used previously and food was selected, starting a new crafting list and selecting Food "None" seems to do nothing. The plugin uses the last remembered food instead.
Also, in this scenario, the plugin makes a check for the food buff after every craft and attempts to use the last remembered food. If the food is not found, it starts working and completes one craft, but then stands up and attempts to use the last remembered food again -- after every single craft.

I hope this helps.
Much appreciated!

**Comment by Junie-774** [comment]
Ty for the bug! Simple feex, has been pushed
