### ISSUE TITLE
[Bug] Medicine does not get refreshed in between crafts after expiring

### ISSUE THREAD

**Issue by redeven** [Junie-774/CraftingList#7]
Issue:

Setting a large crafting list (eg 50 crafts of a single item) that uses medicine does not refresh it after expiring, causing all subsequent crafts to fail. It will only pop one on start and then let it fall off after 15mins.
I haven't been able to test food falling off yet, but if the validation is the same for both, it's likely to work the same.

**Comment by Junie-774** [comment]
Was an issue (typo :playdead:) with detecting whether medicated buff was active, hopefully feex
