### ISSUE TITLE
How to quickcraft thousands of items

### ISSUE THREAD

**Issue by Tatsu941** [Junie-774/CraftingList#8]
hey,
not sure if I overlooked something or if the feature is not yet available but I would like an option to quickcraft thousands of items because I produce alot of housing walls like Cafè Walls or such which just need aloooot of items to be thrown into the company workshop where hq doesnt matter ^^
thanks in advance
Tatsu#1996

**Comment by Junie-774** [comment]
auto quicksynth isn't an available feature yet, though it's somewhere on the backlog. It hasn't hit any of my personal use cases so its gone a bit ignored, though there's some boilerplate code to start working on it. I still need to figure out if/how it's possible to do. While it's not on the top of the list of new features to implement, it's definitely on there.

In the meantime you can simulate this (though much more slowly) by making a macro with a single groundwork and using that

**Comment by Tatsu941** [comment]
> 

Should be possible by taking the time it needs to quickcraft an item, ~3 secs x the amount and then just putting in the value of the Items left (max 99) and putting it in the quick craft number field?

Also a single groundwork sadly isnt even enough XD

But thanks and I mean I would even pay you to implement it if thats a motivator lol

regards
Tatsu#1996 (dc)
