### ISSUE TITLE
Please add the old macro system back

### ISSUE THREAD

**Issue by Mafuyu0** [Junie-774/CraftingList#9]
I understand having inhouse macros could be useful for some, but the fact that this plugin used ingame macros was actually a major plus for me vs other plugins that do the same thing.

The thing is, I don't always have dalamud injected or want to rely on this plugin for simple tasks (like maybe I only have enough mats or time for 1 or 2 crafts). The former will be especially true on new patches / game hotfixes, when dalamud isn't updated yet. This means getting "locked out" of access to the inhouse macros. 

The only way to combat these concerns is to maintain a copy of all the inhouse macros as ingame macros, which was my original gripe with the other crafting plugins: Having to always maintain macros in two different places.

Overall, this new system does the complete opposite of it's intention for me. I think having some kind of option for "Macro type" where you can choose between inhouse vs ingame would be best.

**Comment by Junie-774** [comment]
This is good feedback, thank you. Honestly I kinda wasn't expecting anyone to prefer the old macros, but I did leave the code for them in place. I'll be working on an option to use either type of macro in a way that works cleanly

**Comment by Junie-774** [comment]
ok, old macros have been re-added, and reworked internally so that everything's all nice and works well with each other. Upcoming feature to include smart-wait with them as well. Please look forward to it.
